# Generated by Django 4.0.4 on 2022-04-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['lastname']},
        ),
    ]
