# Generated by Django 4.0.4 on 2022-04-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_members_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English', models.CharField(max_length=255)),
                ('French', models.CharField(max_length=255)),
                ('Arabic', models.CharField(max_length=255)),
            ],
        ),
    ]
